ALTER TABLE materials ADD COLUMN supplier VARCHAR(200);
ALTER TABLE materials ADD COLUMN origin VARCHAR(200);
ALTER TABLE materials ADD COLUMN certified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE materials ADD COLUMN cost_cents BIGINT;
ALTER TABLE materials ADD COLUMN currency VARCHAR(3);

